#!/bin/bash
if [[ -z $1 || ! -d $1 ]]; then
    echo "Usage: ./mvndefault MAVEN_DIR"
    exit 1
fi

setup_enviroment() {
    local maven_dir=$1
    if [ -z "$M2_HOME" ]; then
        echo "Maven Home (M2_HOME) not set"
        exit 1
    fi
    local link_path=`realpath $M2_HOME`
    ln -s -f $maven_dir ${link_path%/apache-*}/current
}

setup_enviroment $1
